### ISSUE TITLE
Error: spawn eye ENOENT in window

### ISSUE THREAD

**Issue by Myeongjoon** [RubenVerborgh/EyeServer#10]
I trying to use eyeserver with window

eye command works, but eyeserver 8000 make error.

![fdas](https://cloud.githubusercontent.com/assets/17864835/16712970/104165e2-46d3-11e6-8bde-82387e244419.png)

How can I avoid this error?

**Comment by RubenVerborgh** [comment]
It's strange that `eye` works then. In what folder is your `eye` executable? What is your `PATH` variable set to?

**Comment by Myeongjoon** [comment]
This picture is eye command in home directory.

![1](https://cloud.githubusercontent.com/assets/17864835/16732813/e299487a-47b9-11e6-889e-2201714151e0.png)


This picture is path setting.

![2](https://cloud.githubusercontent.com/assets/17864835/16732778/bc7aad0a-47b9-11e6-9bf6-579e4f84a75f.png)

**Comment by RubenVerborgh** [comment]
Looks like the `eye` command is installed locally in your current folder. Can you try it from any other folder to confirm?
You need to either move it to one of the folders already in your `PATH`, or add your current folder to `PATH`.

**Comment by Myeongjoon** [comment]
I think current folder did not have `eye` command and eye is in `path`.
because any folder can use `eye` command.


This picture is `dir` command in current folder
![1](https://cloud.githubusercontent.com/assets/17864835/16785281/3342aadc-48c8-11e6-9562-bf7c7d2e4f92.png)


This picture is `eye` command in `C:\` folder
![2](https://cloud.githubusercontent.com/assets/17864835/16785286/37e17014-48c8-11e6-827e-070f58d0ef28.png)

This picture is `eyeserver` command in `c:\` folder
![3](https://cloud.githubusercontent.com/assets/17864835/16785352/8de7aef6-48c8-11e6-96ae-60bb912f4401.png)

**Comment by RubenVerborgh** [comment]
Hmm, I'm not a Windows users and have no idea what happens here. It seems that Node.js, for some reason, can't find the `eye` command.

Perhaps [this discussion](https://github.com/nodejs/node-v0.x-archive/issues/5841) is related. However, the bug seems to be closed. Are you running the latest version of Node.js?

**Comment by Myeongjoon** [comment]
I found error location, I will pull-request
