### ISSUE TITLE
ERROR: Could not start EyeServer

### ISSUE THREAD

**Issue by So-hyun** [RubenVerborgh/EyeServer#12]
Hi 
I downloaded eveserver through a npm.
eye command works, but eyeserver 8000 make error.

![issue](https://cloud.githubusercontent.com/assets/17605782/16951888/d95d7328-4e01-11e6-8d67-e0604476fcf4.PNG)

I considered #10 but could not find the problem.
How can I solve the error?

**Comment by So-hyun** [comment]
**'/tmp has no write permission'** error is tried through administrator command prompt

**Comment by Myeongjoon** [comment]
I think `c:\tmp` folder did not exist.
So make `tmp` folder in `C:\`

**Comment by So-hyun** [comment]
Thank you!! :)
