### ISSUE TITLE
Error : eye --nope --pass tmp/1 --wcache tmp1 /tmp/node_3448_0/0.tmp

### ISSUE THREAD

**Issue by Myeongjoon** [RubenVerborgh/EyeServer#13]
I am trying to use eyeserver in **window 9 OS**. 

After install `curl`,`cturtle`,`swipl`,`eye` and command well in cmd, but `eyeserver 8000` command make error.

![error](https://cloud.githubusercontent.com/assets/17864835/19139228/b54693ee-8bbd-11e6-8234-5a327dca2fa6.png)

I will find why this error evoke.

**Comment by bdevloed** [comment]
A shameless plug :) :
A more convenient way to run eye and eyeserver using Docker:
https://hub.docker.com/r/bdevloed/eyeserver/

**Comment by RubenVerborgh** [comment]
@Myeongjoon Awesome, where did you find Windows 9? :wink:

The error message gives you a hint: "/tmp has no write permission". Can you create a tmp folder and make it writeable?
