### ISSUE TITLE
what is the "_:e_Man_1"

### ISSUE THREAD

**Issue by scenaristeur** [RubenVerborgh/EyeServer#16]
Working on RDF visualisation from several years, i'd like to put a reasoner in my javascript webapps, so I've tried the command from my Linux as mentioned in the README.md like this : 

```
curl "http://eye.restdesc.org/?data=http://eulersharp.sourceforge.net/2003/03swap/socrates.n3&query=http://eulersharp.sourceforge.net/2003/03swap/socratesF.n3"
```

The result  is : 
```
PREFIX : <http://www.agfa.com/w3c/euler/socrates#>

:Socrates a _:e_Man_1.
:Socrates a :Mortal.

```

Could you explain me what is the "_:e_Man_1"
thxs

**Comment by RubenVerborgh** [comment]
It is a [blank node](https://www.w3.org/TR/rdf11-concepts/#section-blank-nodes), i.e., a resource that is represented with a local identifier rather than an IRI.
