### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by wnmills3** [RubenVerborgh/EyeServer#20]
BLUF: it appears the eyeserver can not spawn eye and there is only the /opt/eye/bin/eye.sh and no eye executable that I can find (there is the /opt/eye/lib/eye.pvm though)

I have followed the installation instructions here:
http://eulersharp.sourceforge.net/README.MacOSX
to install eye correctly (see version displayed below for eye, swipl, carl, cturtle, node, and npm)
but when I run: eyeserver 8000 I get this error:

wnm3MacBook:bin wnm3$ eyeserver 8000
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn eye ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

wnm3MacBook:bin wnm3$ /opt/eye/bin/eye.sh --version
eye --version
EYE v18.1105.2012 josd
SWI-Prolog 7.6.4 (x86_64-darwin15.6.0): Jan 12 2018, 14:07:02
starting 26 [msec cputime] 46 [msec walltime]
wnm3MacBook:bin wnm3$ swipl --version
SWI-Prolog version 7.6.4 for x86_64-darwin15.6.0
wnm3MacBook:bin wnm3$ carl --version
carl version 1.0.3

Usage: carl [-b=base-uri] [-o=output-file] [input-files]
wnm3MacBook:bin wnm3$ cturtle --version
cturtle version 1.0.6-SNAPSHOT

Usage: cturtle [-b=base-uri] [-o=output-file] [-f=(nt|n3p|n3p-rdiv)] [input-files]

wnm3MacBook:bin wnm3$ node -v
v11.0.0
wnm3MacBook:bin wnm3$ npm -v
6.4.1

I am running XQuartz.app v2.7.11 and logged out/in before attempting to run the eyeserver.

Running as sudo doesn't have any effect to resolve the problem.

**Comment by wnmills3** [comment]
Forgot the PATH variable:

wnm3MacBook:bin wnm3$ echo $PATH
/csnext/eye/carl:/csnext/eye/cturtle:/Applications/SWI-Prolog.app/Contents/MacOS:/Users/wnm3/.local/bin:/Users/wnm3/anaconda3/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/wnm3/.nvm/versions/node/v8.9.1/bin:/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/mysql/bin/:/Users/wnm3/Library/Android/sdk/tools:/Users/wnm3/Library/Android/sdk/tools/bin:/Users/wnm3/Library/Android/sdk/platform-tools

Not sure if this is an issue:
/tmp is a symbolic link to /private/tmp
but I can touch /tmp/junk and it creates /private/tmp/junk as expected (e.g., saw #12 referencing write permissions).

**Comment by wnmills3** [comment]
Based on #8 I have also added /opt/eye/bin to $PATH and I've created the symbolic link from eye to eye.sh in the /opt/eye/bin directory. This has changed the error to:

wnm3MacBook:bin wnm3$ eyeserver 8000
fs.js:144
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:144:11)
    at Object.unlink (fs.js:954:14)
    at F.release (/Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/node_modules/resourcecache/lib/resourcecache.js:176:8)
    at /Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/lib/eye.js:182:30
    at Array.forEach (<anonymous>)
    at eyeFinished (/Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/lib/eye.js:181:19)
    at Socket.<anonymous> (/Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/lib/eye.js:162:9)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)

**Comment by RubenVerborgh** [comment]
Note that Node 11 is unstable (as are all uneven versions); can you test on 10?

**Comment by wnmills3** [comment]
sure, will try to get that set up, thx

**Comment by wnmills3** [comment]
Same issue:
wnm3MacBook:graceful-fs wnm3$ node -v
v10.13.0
wnm3MacBook:graceful-fs wnm3$ eyeserver 8000
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:936:14)
    at F.release (/Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/node_modules/resourcecache/lib/resourcecache.js:176:8)
    at /Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/lib/eye.js:182:30
    at Array.forEach (<anonymous>)
    at eyeFinished (/Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/lib/eye.js:181:19)
    at Socket.<anonymous> (/Users/wnm3/.nvm/versions/node/v8.9.1/lib/node_modules/eyeserver/lib/eye.js:162:9)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)

**Comment by RubenVerborgh** [comment]
Thanks, will investigate.

**Comment by wnmills3** [comment]
It must be late for you -- it can wait until tomorrow or when you have time. Thank you.

**Comment by RubenVerborgh** [comment]
Ah well, nothing like a good bug in the evening 🙂

**Comment by wnmills3** [comment]
Is it possible that when eye.js calls to remove the temporary file it doesn't pass a callback so it is null in the resourcecache.js? the console.log I added shows callback is undefined:

  release: function (fileName, callback) {
console.log("callback: "+callback+" fileNames: "+JSON.stringify(this.fileNames)+" for fileName: "+fileName);
    delete this.fileNames[fileName];
    fs.unlink(fileName, callback);
  },

and the call in eye.js only passes the resource without any callback...
        resources.forEach(function (resource) {
console.log("resource: "+resource);
          self.resourceCache.release(resource);
        });

**Comment by wnmills3** [comment]
the console.logs above print:
resource: /tmp/node_74446_0/0.tmp
callback: **undefined** fileNames: ["/tmp/node_74446_0/0.tmp"] for fileName: /tmp/node_74446_0/0.tmp

**Comment by RubenVerborgh** [comment]
> Is it possible that when eye.js calls to remove the temporary file it doesn't pass a callback so it is null in the resourcecache.js?

Yes, that was it. Earlier versions of Node didn't require that (this lib is 7 years old).

**Comment by wnmills3** [comment]
I believe the tmp file is getting unlinked so perhaps (kludge...) surround by try/catch ;^)

**Comment by RubenVerborgh** [comment]
Should be fixed in v1.1.2.

**Comment by wnmills3** [comment]
thx, I'm running with the kludge for now:
    try {
      fs.unlink(fileName, callback);
   } catch (e) {}

EYE server running on http://localhost:8000

**Comment by RubenVerborgh** [comment]
Why the kludge though? v1.1.2 works fine here on Node v10. Also very unlikely that the kludge will work given that try/catch is sync, but unlink is async.
