### ISSUE TITLE
Move eye.js to a separate repo

### ISSUE THREAD

**Issue by pheyvaer** [RubenVerborgh/EyeServer#21]
What do you think about moving [eye.js](https://github.com/RubenVerborgh/EyeServer/blob/master/lib/eye.js) to separate repo/library? I made something similar for one of my projects, but it would be nice to have a single one that can be easily reused.

**Comment by RubenVerborgh** [comment]
> a single one that can be easily reused.

It's exported from this library as `Eye` though: https://github.com/RubenVerborgh/EyeServer/blob/master/package.js

**Comment by pheyvaer** [comment]
Nice! Didn't see that.
