### ISSUE TITLE
Error: spawn eye ENOENT

### ISSUE THREAD

**Issue by SergioML9** [RubenVerborgh/EyeServer#8]
Hi, 

I'm getting the following error when I try to run EyeServer with 'eye server 8000' on Mac.

Thanks.

![captura de pantalla 2015-09-25 a las 12 50 41](https://cloud.githubusercontent.com/assets/10586800/10098771/0dc1024c-6384-11e5-90f2-cf6708f79d75.png)

**Comment by RubenVerborgh** [comment]
Do you have the `eye` command installed on your machine? What version of Node.js are you using?

**Comment by SergioML9** [comment]
I don't think so, I have installed the EYE reasoner and then the EYE Server following the instructions, but if I try to execute 'eye' command I get 'command not found'. My Node.js version is 4.1.1.

![captura de pantalla 2015-09-25 a las 12 57 12](https://cloud.githubusercontent.com/assets/10586800/10098911/3c5aebc6-6385-11e5-94e4-9992056d0713.png)

**Comment by RubenVerborgh** [comment]
Alright, you should make sure that the `eye` command is in a place where it can be found by the system. I would recommend putting it in the `PATH` environment variable:
```
export PATH=$PATH:/opt/eye/bin
```

**Comment by SergioML9** [comment]
Same error after putting it in the PATH environment variable:

![captura de pantalla 2015-09-25 a las 13 09 04](https://cloud.githubusercontent.com/assets/10586800/10099114/e12a5c9e-6386-11e5-964d-13011117128d.png)

If I try to run eye command I get 'command not found', but if I run eye.sh it works, as you can see in the screenshot.

**Comment by RubenVerborgh** [comment]
Alright, then you still need to
```
sudo ln -s /opt/eye/bin/eye.sh /opt/eye/bin/eye
```

**Comment by SergioML9** [comment]
Solved, thank you very much !

**Comment by RubenVerborgh** [comment]
You're welcome!
