### ISSUE TITLE
can not read local file

### ISSUE THREAD

**Issue by Myeongjoon** [RubenVerborgh/EyeServer#9]
hello I am studying about semantic web with eye.

If I access eye server with data.n3 & query.n3 in cloud
URL : http://localhost:8000/?data=http://104.199.143.230:8080/data.n3&query=http://104.199.143.230:8080/query.n3

I can gain result.

```
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.agfa.com/w3c/euler/socrates#>
PREFIX q: <http://www.w3.org/2004/ql#>

:hello2 rdfs:subClassOf :helloAPM.
:hello rdfs:subClassOf :helloAPM.
:hello3 rdfs:subClassOf :helloAPM.
```
But if I access with data.n3(same as cloud file) in local file:///Users/kimmyongjoon/NetBeansProjects/tourAPI/data/data.n3
URL : http://localhost:8000/?data=file:///Users/kimmyongjoon/NetBeansProjects/tourAPI/data/data.n3&query=http://104.199.143.230:8080/query.n3

I can not result : result looks like can not read local file
```
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX q: <http://www.w3.org/2004/ql#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://www.agfa.com/w3c/euler/socrates#>
```

How can I access with local file ?? or i need to upload it to cloud?

**Comment by RubenVerborgh** [comment]
This is a safety feature, as otherwise internal files of the server might be exposed.

In order to use local files, set up a local Web server which hosts the files. (For example, `http://localhost/files/data.n3`.)

**Comment by Myeongjoon** [comment]
OK. thanks 
I will set up local web server.
